### ISSUE TITLE
Script is asking for preferred editor, but is using nano the next time something needs to be edited

### ISSUE THREAD

**Issue by SamsiFPV** [lemniskett/archbox#1]
The script asks for my preferred editor (which i obviously replied vim) when editing the mirrorlist, but is using nano when you need to edit the locale.

**Comment by lemniskett** [comment]
This is intended, some editors like `nvim` is provided by package `neovim`, different name, thus its installation can't be automated (it could be, but a bit complicated). Yeah I can use `pkgfile` to find what provides what, but there are multiple packages those provide a same executable. package `gvim` and `vim` provides `vim`, etc.
