### ISSUE TITLE
ChromeOS

### ISSUE THREAD

**Issue by acoul** [lemniskett/archbox#11]
Greetings,

does archbox support ChromeOS ?

**Comment by lemniskett** [comment]
Hi there :)

The last time i tried this in ChromeOS, I can't get steam to work, not sure if it's because of Archbox or my device issue (I'm using ChromeOS with Brunch framework). the rest seem to work fine, but you probably want [Crouton](https://github.com/dnschneid/crouton) instead.

**Comment by acoul** [comment]
I found archbox from [this thread](https://www.reddit.com/r/archlinux/comments/gumwce/just_managed_to_install_arch_linux_in_chroot_in/) looking for a way to install Arch linux on my chromebook on a chroot enviroment.

to the best of my knowledge [Crouton](https://github.com/dnschneid/crouton) supports only debian/ubuntu.

**Comment by lemniskett** [comment]
That's exactly my thread!

**Comment by acoul** [comment]
FWIW [Sommelier](https://github.com/dnschneid/crouton/wiki/Sommelier-%28A-more-native-alternative-to-xiwi%29) states that it supports hardware acceleration on platforms with "xorg" target support.

I am in the process of evaluating the best method to integrate Arch linux on my new chromebook

**Comment by lemniskett** [comment]
Ah yes, I deleted it because most of the guide is automated with Archbox. The only thing you need to do is to install sommelier. the easiest way to do it is to install it with [Chromebrew](https://skycocker.github.io/chromebrew/).

**Comment by lemniskett** [comment]
I guess that's it :)

**Comment by acoul** [comment]
I will eventually get back into this FWIW

I am highly interested on the chroot approach while directly sharing/using the X system

thanks so much for the feedback

**Comment by lemniskett** [comment]
Nice, Aight then.

**Comment by lemniskett** [comment]
Btw, I have added a guide to setup Archbox in ChromeOS, although there are some issues.

**Comment by acoul** [comment]
this new [Installation (ChromeOS)](https://github.com/lemniskett/archbox/blob/master/CROS_INSTALL.md) is very helpful. thank you
