### ISSUE TITLE
Archbox using the wrong PATH environment variable.

### ISSUE THREAD

**Issue by meisme-dev** [lemniskett/archbox#15]
Archbox is using my host NixOS system's `PATH` environment variable.
Screenshot
![Screenshot_20211117_205709](https://user-images.githubusercontent.com/49573906/142337222-2978c3ba-f865-4ba9-be32-b60f31d5a5e7.png)

I can confirm the binaries exist in `/bin`.
Here is my config:
```nix
{ config, pkgs, ... }:

let
    archbox = pkgs.stdenv.mkDerivation rec {
        name = "archbox";
        src = pkgs.fetchFromGitHub {
            owner = "lemniskett";
            repo = "archbox";
            rev = "6ab44021605ff7592692562871aa654eec1ed6bb";
            sha256 = "0qgar6w2q1wsglx3zyj02mygypxs6bplrj43k61bkwz9g9d31yw5";
        };
        sourceRoot = ".";
        installPhase = ''
            mkdir -p $out
            cd source
            export FORCE_INSTALL_CONFIG=1
            export ETC_DIR=$out/etc
            export PREFIX=$out
            export ARCHBOX_USER=meisme_arch
            export MOUNT_RUN=no
            ${pkgs.bash}/bin/bash install.sh
        '';
    };
in
{
    environment.systemPackages = [ archbox ];
    environment.etc = { 
        "archbox.conf" = { 
            source = "${archbox}/etc/archbox.conf";
        };
    };
}
```

**Comment by lemniskett** [comment]
Actually, all binaries are stored in /usr/bin
https://github.com/lemniskett/archbox#archbox-didnt-recognize-commands

**Comment by meisme-dev** [comment]
I can't apply the fix since /nix/store is a readonly file system. Is there any way to bypass that?

**Comment by meisme-dev** [comment]
![Screenshot_20211117_211545](https://user-images.githubusercontent.com/49573906/142339070-5ef432ff-1508-4ff6-935b-47870f56a1f9.png)

**Comment by lemniskett** [comment]
In Nix, configuration is done in the installPhase
https://github.com/lemniskett/archbox/blob/master/NIXOS_INSTALL.md#declarative-nix

**Comment by meisme-dev** [comment]
My bad, didn't see that. Thanks!
