### ISSUE TITLE
How do I use input methods?

### ISSUE THREAD

**Issue by sugarykeytone** [lemniskett/archbox#16]
This is pretty usable, but there is one problem.
I can't use input methods, which are used for entering special characters like Cyrillic and CJK.
Is there a chance that I can run them properly in Archbox?
As a reference, I'll specify my environment here.
OS: NixOS 21.11 Unstable
DE: KDE Plasma

**Comment by lemniskett** [comment]
Actually, i'm not sure how :(
Can you try changing `PRIV` to `sudo -E`?

**Comment by sugarykeytone** [comment]
I'll try that. Also how do I restart the chroot?

**Comment by sugarykeytone** [comment]
![image](https://user-images.githubusercontent.com/90227297/142363310-1210d2ee-0ea4-4ec2-954e-a905c61a4b0e.png)
![image](https://user-images.githubusercontent.com/90227297/142363351-2e8e7f3c-875d-4630-8f78-6ae8f2989650.png)
Doesn't seem to work right because of the quotes...

**Comment by sugarykeytone** [comment]
Using my patched version, I can confirm that this works with `sudo -E`.
