### ISSUE TITLE
SteamDeck support?

### ISSUE THREAD

**Issue by zohozer** [lemniskett/archbox#19]
I do have a SteamDeck with SteamOS 3.4 (Arch distro) and I would like to install this software on my machine but I do not know if is supported and if so how to install-it.

Best regards.

**Comment by parkerlreed** [comment]
There's a well established way of doing this for the Deck. Distrobox!

https://github.com/89luca89/distrobox

There's a root-less method that is perfect for the Deck.

**Comment by lemniskett** [comment]
Agreed with @parkerlreed, as far as I know SteamOS partitions are rewritten each update, So I won't recommend it. distrobox also utilizes podman which is supported by SteamOS out of the box.

But still, you can try installing it by adjusting the location of the chroot directory. but I can't guarantee it as I don't own a deck.

**Comment by zohozer** [comment]
Thank you for the answers. I will take a look at Distribox then.
