### ISSUE TITLE
Perl gives unset locale error

### ISSUE THREAD

**Issue by SamsiFPV** [lemniskett/archbox#3]
When starting perl, it gives an error message about unset locale settings. Like this:
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_MONETARY = "de_CH.UTF-8",
	LC_PAPER = "de_CH.UTF-8",
	LC_TELEPHONE = "de_CH.UTF-8",
	LC_MEASUREMENT = "de_CH.UTF-8",
	LC_TIME = "de_CH.UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

This can be fixed by setting the two unset locales in the .bashrc, like this:
```
export LC_ALL="de_CH.UTF-8"
export LANGUAGE="de_CH.UTF-8"
```

**Comment by lemniskett** [comment]
Alright, this is strange.
Everything is fine in Alacritty and Xfce terminal, but VS Code terminal gives the exact same error.
What terminal emulator do you use?

**Comment by SamsiFPV** [comment]
I use terminator.
That is indeed strange. I expected it to be an perl specific error, not a terminal specific one.

I believe the problem is the way how the different terminal emulators set the environment variables. LANGUAGE ad LC_ALL isn't set at all in my terminator terminal. So obviously setting them fixes the problem.

Weird is that when using perl outside of archbox, without those 2 variables set, perl doesnt give an error. In archbox, without the 2 variables set, it gives the error. So perl somehow is fine without them on my host system, but not in archbox.
