### ISSUE TITLE
Home directory is gone after reboot

### ISSUE THREAD

**Issue by SamsiFPV** [lemniskett/archbox#5]
After rebooting the host system and running archboxinit, the home directory that was mounted from my host system is gone.

**Comment by SamsiFPV** [comment]
Okay, i fixed it. Running archboxinit as root and with the argument "start" will fix the issue. I would suggest to explain the `archboxinit start` and `archboxinit stop` commands in the readme, and mention that archboxinit needs to be run as root, since the mount command only runs with superuser privileges.

Here is my systemd service for those who want archboxinit to run at boot:
```
[Unit]
Description=Archbox init
PartOf=multi-user.target

[Service]
ExecStart=/usr/local/share/archbox/bin/archboxinit start
Type=oneshot
User=root

[Install]
WantedBy=multi-user.target
```

**Comment by lemniskett** [comment]
Ah yeah, i forgot to update readme when implementing this,
